export const CREATE_EMPLOYEE_POSITION = 'CREATE_EMPLOYEE_POSITION';
export const FETCH_EMPLOYEE_POSITIONS = 'FETCH_EMPLOYEE_POSITIONS';
export const UPDATE_EMPLOYEE_POSITION = 'UPDATE_EMPLOYEE_POSITION';
export const DELETE_EMPLOYEE_POSITION = 'DELETE_EMPLOYEE_POSITION';
