export const CREATE_HOTEL = 'CREATE_HOTEL';
export const FETCH_HOTEL = 'FETCH_HOTEL';
export const UPDATE_HOTEL = 'UPDATE_HOTEL';
export const DELETE_HOTEL = 'DELETE_HOTEL';
export const SET_ACTIVE_HOTEL = 'SET_ACTIVE_HOTEL';
