export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const EDIT_POSITIONS_MODAL = 'EDIT_POSITIONS_MODAL';
export const EDIT_ROOM_TYPE_MODAL = 'EDIT_ROOM_TYPE_MODAL';
export const EDIT_EMPLOYEES_MODAL = 'EDIT_EMPLOYEES_MODAL';
export const EDIT_GUEST_MODAL = 'EDIT_GUESTS_MODAL';
export const EDIT_SERVICE_MODAL = 'EDIT_SERVICE_MODAL';
