export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

export const EDIT_POSITIONS_MODAL = 'EDIT_POSITIONS_MODAL';
export const EDIT_ROOM_TYPE_MODAL = 'EDIT_ROOM_TYPE_MODAL';
