export const CREATE_ROOM_TYPE = 'CREATE_ROOM_TYPE';
export const FETCH_ROOM_TYPES = 'FETCH_ROOM_TYPE';
export const UPDATE_ROOM_TYPE = 'UPDATE_ROOM_TYPE';
export const DELETE_ROOM_TYPE = 'DELETE_ROOM_TYPE';
